### ISSUE TITLE
Gerbil does not work with the Spring dependencies added in qa.commons

### ISSUE THREAD

**Issue by Suganya31** [dice-group/NLIWOD#64]
When the following two dependencies are excluded, it works fine.
<dependency>
	    	<groupId>org.springframework.boot</groupId>
	    	<artifactId>spring-boot-starter-web</artifactId>
</dependency> 
 <dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-test</artifactId>
</dependency>

These dependencies were added in the following commit. Added knowledge card utility

https://github.com/dice-group/NLIWOD/commit/f512d9d6379ac835b251ef0717457880bb9619e7

@LukasBluebaum Could you please tell me if these two dependencies are needed?

**Comment by LukasBluebaum** [comment]
They are needed to start a spring application to create knowledge cards for DBpedia resources, which you are not using in gerbil I guess. So if it works after excluding them, it should be fine I think.

**Comment by RicardoUsbeck** [comment]
If you delete 
 * qa.commons/src/main/java/org/aksw/qa/commons/KnowledgeCard/KnowledgeCardApplication.java
 * qa.commons/src/main/java/org/aksw/qa/commons/KnowledgeCard/KnowledgeCardController.java
 * and line 27 https://github.com/dice-group/NLIWOD/commit/f512d9d6379ac835b251ef0717457880bb9619e7#diff-016d32822fe2dececa5fd50d7c513b36R27 

and incorporate
```
HashSet<Field> answer = knowledgeCardCreator.process(url);
String prettyString = JsonUtils.toPrettyString(answer);
```
 into the function knowledgeCardCreator.process(String url), then we can also remove the dependencies and end up with a java lib rather than a webservice but this is fine

**Comment by LukasBluebaum** [comment]
That is better, I'll change that.

**Comment by LukasBluebaum** [comment]
Changed the knowledge card module to a java lib and removed the dependencies in: bafbac16c32a42c06a21f0e54d668f60c5aa9b4a
